project:
  name: TopComment
  id: topcomment-382512
  region: europe-west2
  zone: europe-west2-a

vm_instances:
  service_account_credentials: configs/cloud_sdk/topcomment-382512-ff0807643047.json
  service: compute
  instance_template: cloud_sdk/instance_template.yaml
  num_instances: 2

vpc_network:
  network:
    name: tc-network
    ip_cidr_range: 10.0.0.0/16
  subnet:
    name: tc-subnet
    ip_cidr_range: 10.0.0.0/24
  firewall:
    name: allow-all
    priority: 1000
    direction: INGRESS
    sourceRanges:
      - 0.0.0.0/0
    allowed:
      - IPProtocol: tcp
        ports:
          - "0-65535"
      - IPProtocol: udp
        ports:
          - "0-65535"
      - IPProtocol: icmp
