name: tc-template
machineType: zones/europe-west2-a/machineTypes/n2-standard-2
disks:
  - boot: true
    autoDelete: true
    initializeParams:
      diskSizeGb: 50
      sourceImage: projects/debian-cloud/global/images/family/debian-10
      diskType: projects/topcomment-382512/zones/europe-west2-a/diskTypes/pd-ssd
networkInterfaces:
  - network: projects/topcomment-382512/global/networks/tc-network
    subnetwork: projects/topcomment-382512/regions/europe-west2/subnetworks/tc-subnet
    accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
    networkTier: PREMIUM
serviceAccounts:
  - email: tc-mig-sa@topcomment-382512.iam.gserviceaccount.com
    scopes:
      - https://www.googleapis.com/auth/compute
metadata:
  items:
    - key: startup-script
      value: cloud_sdk/startup_script.sh
    - key: certificate-refresh-interval
      value: 9999
tags:
  items:
    - http-server
    - https-server
description: Instance template for running Selenium tests
